<?php $collection = $block->getCrudCollection(); ?>
<?php if($collection->count() > 0): ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <table class="data table" id="crud-data-table">
        <caption class="table-caption">Andre Crud Data</caption>
        <thead>
            <tr>
                <th scope="col" class="col title">Title</th>
                <th scope="col" class="col author">Author</th>
                <th scope="col" class="col image">Image</th>
                <th scope="col" class="col created_at">Created At</th>
                <th scope="col" class="col actions">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($collection as $key => $data): ?>
                <tr>
                    <td data-th="Title" class="col title"><?php echo $data->getTitle(); ?></td>
                    <td data-th="Author" class="col author"><?php echo $data->getAuthor(); ?></td>
                    <td data-th="Image" class="col image">
                        <?php if($data->getImage()): ?>
                            <img width="70" height="70" src="<?php echo $block->getBaseUrl().'pub/media/'.$data->getImage(); ?>">
                        <?php else: ?>
                            <p>No Image</p>
                        <?php endif; ?>
                    </td>
                    <td data-th="Date" class="col created_at"><?php echo $data->getCreatedAt(); ?></td>
                    <td data-th="Actions" class="col actions">
                        <?php $id = ($data->getCrudId()) ? $data->getCrudId() : $data['crud_id']; ?>
                        <a href="<?php echo $block->getBaseUrl().'crud/index/view/id/'.$id; ?>" class="action view">
                            <span>View</span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <h2>We couldn't find any records</h2>
<?php endif; ?>
